### ISSUE TITLE
Error running SampleCode.s

### ISSUE THREAD

**Issue by jgfoster** [Wunkolo/OakSim#2]
macOS 10.13.6, Chrome 68.0.3440.84

abort() at Error at jsStackTrace (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:5:18821) at stackTrace (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:5:18992) at Object.abort (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:29:7211) at _abort (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:5:200323) at YB (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:13:134507) at Array.Sz (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:17:127559) at Object.GRa [as dynCall_iiiiii] (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:9:184719) at invoke_iiiiii (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:5:284968) at WC (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:19:111734) at SC (https://wunkolo.github.io/OakSim/lib/unicorn-arm.min.js:19:99989) If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by Wunkolo** [comment]
Hey!
SampleCode.s is more so to test the assembler rather than for the emulation.
The first bytes of "SampleCode" would emit bytes intended to be a visual queue for the assembler and would crash the emulator if it tried to interpret the bytes `Squa` as instructions
![image](https://user-images.githubusercontent.com/644247/43979250-f900d2d6-9c9e-11e8-8988-9b7b1fa7a1d0.png)
If you want to omit the pad-group bytes simply delete these lines here:
![image](https://user-images.githubusercontent.com/644247/43979279-11f8e742-9c9f-11e8-99d7-fd0438c901a7.png)

Though even then it might crash upon execution of the first "bx lr" as the lr register would be an invalid address `0`.

**Comment by jgfoster** [comment]
Then perhaps the file should be renamed "assemblerTest.s" and a comment added saying "Not to be run in the emulator." Also, it would be very nice to have some samples demonstrating the supported features.
